### ISSUE TITLE
Add support for KL110

### ISSUE THREAD

**Issue by 24mu13** [black-sheep-dev/harbour-kasa#2]
Would be nice to have the support for this lamp also.
https://www.tp-link.com/it/home-networking/smart-bulb/kl110/

**Comment by black-sheep-dev** [comment]
In theory turn on/off should already work if you add it via IP.
Do you have one of this bulbs?
If you own one, can you please turn on debug  logging in the app settings and provide me the data.
What I need to add is the dimming function for this bulb. The necessary code for this is already there, but I have no chance to test it. So your turn...

**Comment by 24mu13** [comment]
I added the device and simply tried to switch on and off, without success.
[192.168.2.116.json.txt](https://github.com/black-sheep-dev/harbour-kasa/files/5506005/192.168.2.116.json.txt)

Could be **set_led_on** method instead of **set_relay_state** ? I could try to hack a bit...
Or if you can point me to any kind of reverse-eng-documentation I would be glad to help

**Comment by black-sheep-dev** [comment]
Thanks for the data.
The function **set_led_on** toggles the indication led on the smart plugs.
In the case of a light bulb it use **set_light_state** instead of **set_relay_state** to toggle.
I didn't found any documentation about the smart bulbs, but I think the provided data from you is enough to get this to work.
Need to introduce the light device type in the app.

**Comment by black-sheep-dev** [comment]
I added a feature to the app (0.1.9) to send custom commands to your device.
Will provide you some commands for testing soon.
You can also try to play around yourself. I have some documentation in protocol folder in this repository.

**Comment by 24mu13** [comment]
I always (tried several combinations) get back the following error:
```
{
  "system": {
    "set_light_state": {
      "err_code": -2000,
      "err_msg": "Method not support"
    }
}
```

Probably you already know, but I think we should look here:
https://github.com/plasticrake/tplink-smarthome-api

There is also a very convenient [simulator](https://github.com/plasticrake/tplink-smarthome-simulator) for all tplink devices

**Comment by 24mu13** [comment]
Found it!

To switch on/off:
``{"smartlife.iot.smartbulb.lightingservice":{"transition_light_state":{"on_off":0}}}``

See also:
https://smdn.jp/electronics/TPLinkKasaClient/#examples

Not exactly so easy... but it's feasable now

**Comment by black-sheep-dev** [comment]
Thanks for the link!

I have added the turn on/off and also the brightness feature into the app. 
It is a bit hacky for the moment, but it should work.

Can you please test it?

[harbour-kasa-0.1.10-1.armv7hl.rpm.gz](https://github.com/black-sheep-dev/harbour-kasa/files/5507995/harbour-kasa-0.1.10-1.armv7hl.rpm.gz)
